// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.3
// source: xbc_v2/xbc_agent_event_outbox_service_v2.proto

package xbc_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentEventType int32

const (
	AgentEventType_AGENT_EVENT_UNSPECIFIED                   AgentEventType = 0
	AgentEventType_AGENT_EVENT_REGISTER                      AgentEventType = 1
	AgentEventType_AGENT_EVENT_UNREGISTER                    AgentEventType = 2
	AgentEventType_AGENT_EVENT_ACTIVATE                      AgentEventType = 3
	AgentEventType_AGENT_EVENT_UPDATE                        AgentEventType = 4
	AgentEventType_AGENT_EVENT_ONBOARD                       AgentEventType = 5
	AgentEventType_AGENT_EVENT_DEACTIVATE                    AgentEventType = 6
	AgentEventType_AGENT_EVENT_SCENARIO_ACTION_RESULT_REPORT AgentEventType = 7
	AgentEventType_AGENT_EVENT_DUPLICATE                     AgentEventType = 8
)

// Enum value maps for AgentEventType.
var (
	AgentEventType_name = map[int32]string{
		0: "AGENT_EVENT_UNSPECIFIED",
		1: "AGENT_EVENT_REGISTER",
		2: "AGENT_EVENT_UNREGISTER",
		3: "AGENT_EVENT_ACTIVATE",
		4: "AGENT_EVENT_UPDATE",
		5: "AGENT_EVENT_ONBOARD",
		6: "AGENT_EVENT_DEACTIVATE",
		7: "AGENT_EVENT_SCENARIO_ACTION_RESULT_REPORT",
		8: "AGENT_EVENT_DUPLICATE",
	}
	AgentEventType_value = map[string]int32{
		"AGENT_EVENT_UNSPECIFIED":                   0,
		"AGENT_EVENT_REGISTER":                      1,
		"AGENT_EVENT_UNREGISTER":                    2,
		"AGENT_EVENT_ACTIVATE":                      3,
		"AGENT_EVENT_UPDATE":                        4,
		"AGENT_EVENT_ONBOARD":                       5,
		"AGENT_EVENT_DEACTIVATE":                    6,
		"AGENT_EVENT_SCENARIO_ACTION_RESULT_REPORT": 7,
		"AGENT_EVENT_DUPLICATE":                     8,
	}
)

func (x AgentEventType) Enum() *AgentEventType {
	p := new(AgentEventType)
	*p = x
	return p
}

func (x AgentEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_enumTypes[0].Descriptor()
}

func (AgentEventType) Type() protoreflect.EnumType {
	return &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_enumTypes[0]
}

func (x AgentEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentEventType.Descriptor instead.
func (AgentEventType) EnumDescriptor() ([]byte, []int) {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP(), []int{0}
}

type AgentEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EventId   int64          `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	DeviceId  string         `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EventType AgentEventType `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=xbc.v2.AgentEventType" json:"event_type,omitempty"`
	Contents  string         `protobuf:"bytes,4,opt,name=contents,proto3" json:"contents,omitempty"`
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP(), []int{0}
}

func (x *AgentEvent) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *AgentEvent) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentEvent) GetEventType() AgentEventType {
	if x != nil {
		return x.EventType
	}
	return AgentEventType_AGENT_EVENT_UNSPECIFIED
}

func (x *AgentEvent) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

// Poll events from xbc-ams-db
type PollAgentEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionNumber int64 `protobuf:"varint,1,opt,name=partition_number,json=partitionNumber,proto3" json:"partition_number,omitempty"`
	Count           int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PollAgentEventRequest) Reset() {
	*x = PollAgentEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollAgentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAgentEventRequest) ProtoMessage() {}

func (x *PollAgentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAgentEventRequest.ProtoReflect.Descriptor instead.
func (*PollAgentEventRequest) Descriptor() ([]byte, []int) {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP(), []int{1}
}

func (x *PollAgentEventRequest) GetPartitionNumber() int64 {
	if x != nil {
		return x.PartitionNumber
	}
	return 0
}

func (x *PollAgentEventRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type PollAgentEventResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Events []*AgentEvent `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
}

func (x *PollAgentEventResponse) Reset() {
	*x = PollAgentEventResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PollAgentEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollAgentEventResponse) ProtoMessage() {}

func (x *PollAgentEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollAgentEventResponse.ProtoReflect.Descriptor instead.
func (*PollAgentEventResponse) Descriptor() ([]byte, []int) {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP(), []int{2}
}

func (x *PollAgentEventResponse) GetEvents() []*AgentEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// Commit events to xbc-ams-db
// Currently, "consumer_name" will be pod name of xbc-outbox-forward-server
// e.g. xbc-outbox-forward-server-0
type CommitAgentEventRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PartitionNumber int64  `protobuf:"varint,1,opt,name=partition_number,json=partitionNumber,proto3" json:"partition_number,omitempty"`
	OffsetId        int64  `protobuf:"varint,2,opt,name=offset_id,json=offsetId,proto3" json:"offset_id,omitempty"`
	ConsumerName    string `protobuf:"bytes,3,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
}

func (x *CommitAgentEventRequest) Reset() {
	*x = CommitAgentEventRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CommitAgentEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitAgentEventRequest) ProtoMessage() {}

func (x *CommitAgentEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitAgentEventRequest.ProtoReflect.Descriptor instead.
func (*CommitAgentEventRequest) Descriptor() ([]byte, []int) {
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP(), []int{3}
}

func (x *CommitAgentEventRequest) GetPartitionNumber() int64 {
	if x != nil {
		return x.PartitionNumber
	}
	return 0
}

func (x *CommitAgentEventRequest) GetOffsetId() int64 {
	if x != nil {
		return x.OffsetId
	}
	return 0
}

func (x *CommitAgentEventRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

var File_xbc_v2_xbc_agent_event_outbox_service_v2_proto protoreflect.FileDescriptor

var file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDesc = []byte{
	0x0a, 0x2e, 0x78, 0x62, 0x63, 0x5f, 0x76, 0x32, 0x2f, 0x78, 0x62, 0x63, 0x5f, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x32, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x06, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x97, 0x01, 0x0a, 0x0a, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0a,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x16, 0x2e, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x58, 0x0a, 0x15, 0x50, 0x6f, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x61, 0x72, 0x74,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x44, 0x0a, 0x16, 0x50, 0x6f, 0x6c,
	0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x86, 0x01, 0x0a, 0x17, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x70,
	0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6f, 0x66, 0x66, 0x73, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x73,
	0x75, 0x6d, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x2a, 0x94, 0x02, 0x0a, 0x0e, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x17, 0x41,
	0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x41, 0x47, 0x45, 0x4e,
	0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52,
	0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e,
	0x54, 0x5f, 0x55, 0x4e, 0x52, 0x45, 0x47, 0x49, 0x53, 0x54, 0x45, 0x52, 0x10, 0x02, 0x12, 0x18,
	0x0a, 0x14, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x56, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x41, 0x47, 0x45, 0x4e,
	0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x04,
	0x12, 0x17, 0x0a, 0x13, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f,
	0x4f, 0x4e, 0x42, 0x4f, 0x41, 0x52, 0x44, 0x10, 0x05, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x47, 0x45,
	0x4e, 0x54, 0x5f, 0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x44, 0x45, 0x41, 0x43, 0x54, 0x49, 0x56,
	0x41, 0x54, 0x45, 0x10, 0x06, 0x12, 0x2d, 0x0a, 0x29, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45,
	0x56, 0x45, 0x4e, 0x54, 0x5f, 0x53, 0x43, 0x45, 0x4e, 0x41, 0x52, 0x49, 0x4f, 0x5f, 0x41, 0x43,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x52, 0x45, 0x50, 0x4f,
	0x52, 0x54, 0x10, 0x07, 0x12, 0x19, 0x0a, 0x15, 0x41, 0x47, 0x45, 0x4e, 0x54, 0x5f, 0x45, 0x56,
	0x45, 0x4e, 0x54, 0x5f, 0x44, 0x55, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x54, 0x45, 0x10, 0x08, 0x32,
	0xad, 0x01, 0x0a, 0x0d, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x78, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x50, 0x6f, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x1d, 0x2e, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6f, 0x6c,
	0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x6f, 0x6c, 0x6c,
	0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x4b, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1f, 0x2e, 0x78, 0x62, 0x63, 0x2e, 0x76, 0x32, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42,
	0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x78, 0x62, 0x63, 0x5f, 0x76, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescOnce sync.Once
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescData = file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDesc
)

func file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescGZIP() []byte {
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescOnce.Do(func() {
		file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescData = protoimpl.X.CompressGZIP(file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescData)
	})
	return file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDescData
}

var file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_goTypes = []interface{}{
	(AgentEventType)(0),             // 0: xbc.v2.AgentEventType
	(*AgentEvent)(nil),              // 1: xbc.v2.AgentEvent
	(*PollAgentEventRequest)(nil),   // 2: xbc.v2.PollAgentEventRequest
	(*PollAgentEventResponse)(nil),  // 3: xbc.v2.PollAgentEventResponse
	(*CommitAgentEventRequest)(nil), // 4: xbc.v2.CommitAgentEventRequest
	(*emptypb.Empty)(nil),           // 5: google.protobuf.Empty
}
var file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_depIdxs = []int32{
	0, // 0: xbc.v2.AgentEvent.event_type:type_name -> xbc.v2.AgentEventType
	1, // 1: xbc.v2.PollAgentEventResponse.events:type_name -> xbc.v2.AgentEvent
	2, // 2: xbc.v2.OutboxService.PollAgentEvent:input_type -> xbc.v2.PollAgentEventRequest
	4, // 3: xbc.v2.OutboxService.CommitAgentEvent:input_type -> xbc.v2.CommitAgentEventRequest
	3, // 4: xbc.v2.OutboxService.PollAgentEvent:output_type -> xbc.v2.PollAgentEventResponse
	5, // 5: xbc.v2.OutboxService.CommitAgentEvent:output_type -> google.protobuf.Empty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_init() }
func file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_init() {
	if File_xbc_v2_xbc_agent_event_outbox_service_v2_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollAgentEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PollAgentEventResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CommitAgentEventRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_goTypes,
		DependencyIndexes: file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_depIdxs,
		EnumInfos:         file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_enumTypes,
		MessageInfos:      file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_msgTypes,
	}.Build()
	File_xbc_v2_xbc_agent_event_outbox_service_v2_proto = out.File
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_rawDesc = nil
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_goTypes = nil
	file_xbc_v2_xbc_agent_event_outbox_service_v2_proto_depIdxs = nil
}
